
import type { Metadata } from 'next';
import NavBar from "@/app/components/navbar";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const handleSearch = () => {
    console.log("Search query:");
  };

  const handleCategoryChange = () => {
    console.log("Category changed:");
  };

  return (
    <html lang="en">
      <body>
     
      <NavBar />
        {children}
      </body>
    </html>
  );
}
