import type { Metadata } from "next";
import {Header} from '@/app/components/header';
import { NavBar } from "@/app/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <NavBar />
      
        {children}
      </body>
    </html>
  );
}
